apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  dsm: '192.168.6.20'
  location: '/volume1'
  protocol: iscsi
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
